version:
  "3.8"

  # SERVICIO PARA MYSQL
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./mysql:/var/lib/mysql
    # SERVICIO PARA LARAVEL
  laravel:
    container_name: laravel
    ports:
      - $LARAVEL_LOCAL_PORT:$LARAVEL_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQL_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www
    build: .
    restart: unless-stopped
    depends_on:
      - mysqldb
    command: php artisan serve --host=0.0.0.0 --port=$LARAVEL_LOCAL_PORT
  #SERVICIO PARA CLIENTE DE MYSQL - ADMINER
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
networks:
  laravel:
